import copy
from libmahjong import PieceType

TUTORIAL_SET = [
    # Player Tiles
    PieceType.ONE_CHARACTER,
    PieceType.ONE_CHARACTER,
    PieceType.SIX_CHARACTER,
    PieceType.SEVEN_CHARACTER,
    PieceType.TWO_PIN,
    PieceType.THREE_PIN,
    PieceType.FOUR_PIN,
    PieceType.FIVE_PIN,
    PieceType.SEVEN_PIN,
    PieceType.ONE_BAMBOO,
    PieceType.SEVEN_BAMBOO,
    PieceType.SOUTH_WIND,
    PieceType.RED_DRAGON,
    # Bot 1 Tiles
    PieceType.ONE_CHARACTER,
    PieceType.TWO_BAMBOO,
    PieceType.THREE_BAMBOO,
    PieceType.FOUR_BAMBOO,
    PieceType.SIX_BAMBOO,
    PieceType.SEVEN_BAMBOO,
    PieceType.EIGHT_BAMBOO,
    PieceType.NINE_BAMBOO,
    PieceType.ONE_PIN,
    PieceType.TWO_PIN,
    PieceType.THREE_PIN,
    PieceType.FOUR_PIN,
    PieceType.SIX_PIN,
    # Bot 2 Tiles
    PieceType.SEVEN_PIN,
    PieceType.EIGHT_PIN,
    PieceType.NINE_PIN,
    PieceType.ONE_CHARACTER,
    PieceType.TWO_CHARACTER,
    PieceType.THREE_CHARACTER,
    PieceType.FOUR_CHARACTER,
    PieceType.SIX_CHARACTER,
    PieceType.SEVEN_CHARACTER,
    PieceType.EIGHT_CHARACTER,
    PieceType.NINE_CHARACTER,
    PieceType.NORTH_WIND,
    PieceType.EAST_WIND,
    # Bot 3 Tiles
    PieceType.SEVEN_PIN,
    PieceType.EIGHT_PIN,
    PieceType.NINE_PIN,
    PieceType.ONE_CHARACTER,
    PieceType.TWO_CHARACTER,
    PieceType.THREE_CHARACTER,
    PieceType.FOUR_CHARACTER,
    PieceType.SIX_CHARACTER,
    PieceType.SEVEN_CHARACTER,
    PieceType.EIGHT_CHARACTER,
    PieceType.NINE_CHARACTER,
    PieceType.NORTH_WIND,
    PieceType.EAST_WIND,
    # Draws
    PieceType.RED_DRAGON,
    PieceType.TWO_BAMBOO,
    PieceType.RED_DRAGON,
    PieceType.FIVE_BAMBOO,
    PieceType.SIX_PIN,
    PieceType.FIVE_CHARACTER,
    PieceType.ONE_CHARACTER,
    PieceType.NORTH_WIND,
    PieceType.NINE_PIN,
    PieceType.FOUR_PIN,
    PieceType.WHITE_DRAGON,
    PieceType.THREE_PIN,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
    PieceType.NORTH_WIND,
]


def get_wall():
    board = copy.deepcopy(TUTORIAL_SET)
    return board[0:-14], board[-14:]
